package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/propitech/worktree-tools/internal/env"
	"github.com/propitech/worktree-tools/internal/ports"
	"github.com/propitech/worktree-tools/internal/services"
)

// provision writes the .env for dest at slot and copies gitignored secrets
// from the primary checkout. Shared vs legacy contract is detected via mise.
func provision(dest, mainPath string, slot int, portBases ports.Bases, svcCfg services.Config, runtimeDir string, stdout io.Writer) error {
	miseTrust(filepath.Join(dest, "mise.toml"))
	miseTrust(filepath.Join(dest, "mise.local.toml"))

	if services.AppEnvVar(dest, "WORKTREE_SERVICES") != "shared" {
		return fmt.Errorf("worktree: %s does not set WORKTREE_SERVICES=shared in its mise [env];\n"+
			"  only shared-services apps are supported — add WORKTREE_SERVICES = \"shared\" to mise.toml [env]", dest)
	}
	if err := provisionShared(dest, slot, portBases, svcCfg, runtimeDir, stdout); err != nil {
		return err
	}
	return provisionCopySecrets(dest, mainPath, stdout)
}

func provisionShared(dest string, slot int, portBases ports.Bases, svcCfg services.Config, runtimeDir string, stdout io.Writer) error {
	app := services.AppEnvVar(dest, "WORKTREE_APP")
	if app == "" {
		return fmt.Errorf("worktree: %s sets WORKTREE_SERVICES=shared but WORKTREE_APP is empty\n"+
			"  WORKTREE_APP must name the app explicitly (SOCK_PREFIX is not the app name)\n"+
			"  refusing to provision — database names would be underivable", dest)
	}

	_, regRuntimeDir := services.EnsureRegistry()
	if runtimeDir == "" {
		runtimeDir = regRuntimeDir
	}

	base, err := services.AppBase(app)
	if err != nil {
		return fmt.Errorf("allocate app base: %w", err)
	}
	redisDB := base + slot
	suffix := ""
	if slot != 0 {
		suffix = fmt.Sprintf("_s%d", slot)
	}
	webPort := portBases.ForSlot(slot).Web

	fmt.Fprintf(stdout, "==> Writing %s/.env (shared: app=%s slot=%d suffix=%q redis_db=%d web=%d)\n",
		dest, app, slot, suffix, redisDB, webPort)

	content := fmt.Sprintf(`# Generated by bin/worktree — shared dev services (plan 0001).
# Isolation is by namespace, not port: a per-app+slot database suffix and a
# Redis DB index. The Postgres/Redis/Mailpit daemons are shared per machine —
# manage them with: worktree services start
WORKTREE_SLOT=%d
WORKTREE_APP=%s
WORKTREE_SERVICES=shared
WORKTREE_DB_SUFFIX=%s
PORT=%d
DB_HOST=localhost
DB_PORT=%d
REDIS_DB=%d
REDIS_URL=redis://localhost:%d/%d
MAIL_SMTP_PORT=%d
MAIL_UI_PORT=%d
`, slot, app, suffix, webPort,
		svcCfg.PGPort, redisDB, svcCfg.RedisPort, redisDB,
		svcCfg.MailSMTPPort, svcCfg.MailUIPort)

	if err := os.WriteFile(filepath.Join(dest, ".env"), []byte(content), 0o644); err != nil {
		return err
	}
	services.CreateDevDB(runtimeDir, svcCfg.PGPort)
	return nil
}

// ensurePrimaryShared provisions the primary checkout (slot 0) when its mise
// env opts into shared services but its .env hasn't been written yet.
func ensurePrimaryShared(mainPath string, portBases ports.Bases, svcCfg services.Config, runtimeDir string, stdout io.Writer) error {
	if services.AppEnvVar(mainPath, "WORKTREE_SERVICES") != "shared" {
		return nil
	}
	if env.Value(filepath.Join(mainPath, ".env"), "WORKTREE_SERVICES") == "shared" {
		return nil
	}
	fmt.Fprintf(stdout, "==> Provisioning primary checkout (slot 0) for shared services\n")
	return provision(mainPath, mainPath, 0, portBases, svcCfg, runtimeDir, stdout)
}

// stripEnvKeys matches lines that carry slot/port keys that must not be
// inherited when copying mise.local.toml from the primary to a new worktree.
var stripEnvKeys = regexp.MustCompile(
	`(?m)^\s*(PORT|DB_HOST|DB_PORT|REDIS_PORT|REDIS_DB|REDIS_URL|MAIL_SMTP_PORT|MAIL_UI_PORT|WORKTREE_SLOT|WORKTREE_APP|WORKTREE_SERVICES|WORKTREE_DB_SUFFIX)\s*=`)

func provisionCopySecrets(dest, mainPath string, stdout io.Writer) error {
	// config/master.key
	masterSrc := filepath.Join(mainPath, "config", "master.key")
	masterDst := filepath.Join(dest, "config", "master.key")
	if fileExists(masterSrc) && !fileExists(masterDst) {
		if data, err := os.ReadFile(masterSrc); err == nil {
			if err := os.MkdirAll(filepath.Dir(masterDst), 0o755); err == nil {
				if err := os.WriteFile(masterDst, data, 0o600); err == nil {
					fmt.Fprintf(stdout, "==> Copied config/master.key\n")
				}
			}
		}
	}

	// Procfile.dev
	procfileDst := filepath.Join(dest, "Procfile.dev")
	if !fileExists(procfileDst) {
		procfileSrc := filepath.Join(mainPath, "Procfile.dev")
		exampleSrc := filepath.Join(dest, "Procfile.dev.example")
		switch {
		case fileExists(procfileSrc):
			if data, err := os.ReadFile(procfileSrc); err == nil {
				if err := os.WriteFile(procfileDst, data, 0o644); err == nil {
					fmt.Fprintf(stdout, "==> Copied Procfile.dev\n")
				}
			}
		case fileExists(exampleSrc):
			if data, err := os.ReadFile(exampleSrc); err == nil {
				if err := os.WriteFile(procfileDst, data, 0o644); err == nil {
					fmt.Fprintf(stdout, "==> Created Procfile.dev from Procfile.dev.example\n")
				}
			}
		}
	}

	// mise.local.toml: copy from primary, stripping port/slot keys.
	miseSrc := filepath.Join(mainPath, "mise.local.toml")
	miseDst := filepath.Join(dest, "mise.local.toml")
	if fileExists(miseSrc) && dest != mainPath {
		if data, err := os.ReadFile(miseSrc); err == nil {
			sc := bufio.NewScanner(strings.NewReader(string(data)))
			var kept []string
			for sc.Scan() {
				if line := sc.Text(); !stripEnvKeys.MatchString(line) {
					kept = append(kept, line)
				}
			}
			if err := os.WriteFile(miseDst, []byte(strings.Join(kept, "\n")+"\n"), 0o644); err == nil {
				fmt.Fprintf(stdout, "==> Copied mise.local.toml (port/slot/namespace keys stripped)\n")
			}
		}
	}

	miseTrust(filepath.Join(dest, "mise.toml"))
	miseTrust(filepath.Join(dest, "mise.local.toml"))

	// rtk filters
	if fileExists(filepath.Join(dest, ".rtk", "filters.toml")) {
		cmd := exec.Command("rtk", "trust")
		cmd.Dir = dest
		if err := cmd.Run(); err == nil {
			fmt.Fprintf(stdout, "==> Trusted rtk filters\n")
		}
	}
	return nil
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func miseTrust(path string) {
	if !fileExists(path) {
		return
	}
	_ = exec.Command("mise", "trust", path).Run()
}
